src/repository.rs

We're pervasively missing this and O_CLOEXEC is IMO quite important for anything caring about security. Rust notably does *not* automatically close fds with `std::process::Command`.
Now...digging into this I do think we should take a dep on cap-std{,-ext} but that's a distinct thread.

repo: Add missing O_CLOEXEC

---

tests/repo.rs

We don't need to heap allocate a whole zeroed buffer here, we can create a virtual reader that returns exactly that number of zeroed bytes dynamically.

tests: Drop an unnecessary vec allocation

---

.github/workflows/rust.yml
Cargo.toml
examples/uki/Containerfile
examples/uki/build
examples/uki/make-image
src/bin/cfsctl.rs
src/bin/composefs-pivot-sysroot.rs
src/dumpfile.rs
src/fs.rs
src/image.rs
src/lib.rs
src/oci/image.rs
src/oci/mod.rs
src/oci/tar.rs
src/selabel.rs

There are some outstanding items here:
`
Closes #29

selinux relabel support

---

.github/workflows/rust.yml

This got introduced by cdcda8d8d80d and I missed it during review because it didn't result in any red on the pull request (but the failing workflow was visible in the Actions tab).

.github/workflows: fix a couple of errors

---

doc/oci.md
examples/unified/.gitignore
examples/unified/Containerfile
examples/unified/build
examples/unified/extra/etc/resolv.conf
examples/unified/extra/usr/lib/dracut/dracut.conf.d/37composefs.conf
examples/unified/extra/usr/lib/dracut/modules.d/37composefs/composefs-pivot-sysroot.service
examples/unified/extra/usr/lib/dracut/modules.d/37composefs/module-setup.sh
examples/unified/extra/usr/lib/kernel/install.conf.d/37composefs.conf
examples/unified/extra/usr/lib/systemd/network/37-wired.network
examples/unified/extra/usr/lib/systemd/system/systemd-growfs-root.service.d/37-composefs.conf
examples/unified/fix-verity
examples/unified/make-image
examples/unified/repart.d/01-esp.conf
examples/unified/repart.d/02-sysroot.conf
examples/unified/run
src/bin/cfsctl.rs
src/fs.rs
src/image.rs
src/lib.rs
src/oci/image.rs
src/oci/tar.rs
src/selabel.rs

This is basically the default mode of operation for `mkcomposefs`, but we're interested in getting exactly the same image as if we had created it from the layer tarballs.
This requires a bit more work, including adding selinux labels and some very careful thinking about the root directory.
This introduces a new `examples/unified` which builds the container in a single `podman build`.  It gets the same result inside and outside (or at least it does for me) and boots up normally.
A preparatory commit defines the inlining constant to 64 and uses it, which means that repositories need to be recreated.
Closes #34
Closes #26

Add support for creating a composefs from a directory

---

.github/workflows/rust.yml
Cargo.toml
src/fs.rs

I tried to publish the crate and it failed.  Fix the reason for that, and check for future failures by doing a publish dry-run on each push.
Also add some bonus dependency pruning!

some fixes to prepare to publish composefs 0.2.0 crate

---

Cargo.toml

In order to provide help, there are missing features.
It seems been removed in 
https://github.com/containers/composefs-rs/commit/3e49e280577b46789a321b78e2ca6d30a74676b8
```
./target/release/cfsctl --help
cfsctl
Usage: cfsctl [OPTIONS] <COMMAND>
Commands:
transaction      Take a transaction lock on the repository. This prevents garbage collection from occurring
cat              Reconstitutes a split stream and writes it to stdout
...
```

Cargo.toml: Add clap features: help, usage

---

src/fs.rs

We use listxattr() with an empty buffer (as documented in the manpage) to query the size of the xattrs that are present.  Unfortunately, this "empty buffer" case hits a shortcut in the xattr code in overlayfs which happens before the overlayfs-internal xattrs are filtered out.
Once we perform the read "for real" we hit the filter path and the returned xattrs are smaller than we were expecting.
Let's deal with that by accepting a smaller return value from the second call and truncating the buffer to that length.
Thanks to Shawn Wang <shawn111@gmail.com> for the report.
Closes #41

fs: workaround quirkly overlayfs listxattr()

---

Cargo.toml
src/dumpfile_parse.rs
src/fs.rs
src/image.rs

Clean up two aspects of importing filesystems:
First: instead of trying to avoid crossing mountpoints (by checking `.st_dev`) in order to use `.st_ino` values as a "unique key" for tracking hardlinks, just take the `(.st_dev, .st_ino)` pair.  This resolves some issues with overlayfs where adjacent files can end up with different `.st_dev`.
Second: we were abusing the first setting of `st_dev` as a flag field to determine if we were `stat()`-ing the root inode or not, which was always a bit evil.  We did this to avoid collecting the mtime of the root directory for determining the newest file in the filesystem.  Let's change our approach here: we can collect the mtime when adding items to their parent directories (which is never done for the root directory). Use a impl on `Inode` to make it …

fs: clean up filesystem import state

---

Cargo.toml
src/fsverity/ioctl.rs
src/fsverity/mod.rs
src/mount.rs
src/repository.rs

First switch to use `rustix::io::Result` since this is a raw low level API and we don't need generic errors.
Change the "wrong algorithm" error to `EILSEQ` which is what the C composefs library is doing today.
Next, add an API that maps the errno values to `Option` for callers that want to not have missing verity be a fatal error.

fsverity: Use rustix Result, add fs_ioc_measure_verity_optional

---

src/fs.rs

See https://github.com/bytecodealliance/rustix/pull/1061#issuecomment-2518467534 Basically current rustix 0.38 sometimes may expose the element type as a signed or unsigned variant, depending on the version of linux-raw-sys and rustix feature flags.
Add a cast to work around this; if we cared to drop the unsafe we could use the zerocopy crate.

fs: Work around rustix listxattr c_char wonkiness

---

Cargo.toml
src/fs.rs

Followup to https://github.com/containers/composefs-rs/pull/50
---
ref https://lwn.net/Articles/995814/ etc.
I also did a PR for tar-rs: https://github.com/alexcrichton/tar-rs/pull/392
Thanks to the maintainer who helped me on Discord
to know the right API to call here.

Use zerocopy instead of unsafe transmute

---

Cargo.toml
src/bin/composefs-pivot-sysroot.rs
src/dumpfile_parse.rs
src/fsverity/digest.rs
src/oci/image.rs
tests/repo.rs

I was using this in the previous composefs rust code and I find it useful. Prep for more testing work.

tests: Use similar-asserts

---

Cargo.toml

This is what's in C9S (a primary dev target for me) at the moment. The claimed rationale for the bump around lifetime elison rules doesn't seem correct (this builds just fine for me with 1.82).
I suspect it's more newer clippy has newer suggestions.

build-sys: Lower rust-version to 1.82

---

src/fs.rs

I was just skimming this code and noticed
we were incorrectly using `write`.
I'd like to reopen that conversation about using
cap-std and especially cap-std-ext, which
would have fixed several of these bugs
with our nice high level helper API like
https://docs.rs/cap-std-ext/latest/cap_std_ext/dirext/trait.CapStdExtDirExt.html#tymethod.atomic_replace_with
Anyways for now I just fixed the implementation here.
- Add a doc comment
- Add O_CLOEXEC
- Use `write_all` instead of a single `write` (!)
- Add a test
(Also a different bug, this function takes a `Stat` but
ignores everything except st_mode, but we can fix that later)

fs: Two fixes for set_file_contents

---

Cargo.toml
src/dumpfile_parse.rs

This commit adds the `test_with` crate and skips the tests that require `mkcomposefs`.
It uses use the minimal configuration of `tests_with` and with that we now pull in 229 `cargo tree` lines vs the pervious 217 (fwiw, the default configuration of tests_with incrases the crates from 217 to 497). Even the extra 12 might be too much for this tiny feature, feel free to close again if you feel this is not worth it.

tests: use `test_with` and skip tests that need `mkcomposefs`

---

src/selabel.rs

```
warning: manual case-insensitive ASCII comparison
--> src/selabel.rs:248:16
|
248 |             if key.trim().to_ascii_uppercase() == "SELINUXTYPE" {
|                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#manual_ignore_case_cmp
= note: `#[warn(clippy::manual_ignore_case_cmp)]` on by default
help: consider using `.eq_ignore_ascii_case()` instead
|
248 |             if key.trim().eq_ignore_ascii_case("SELINUXTYPE") {
|                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

selabel: Fix clippy lint

---

examples/bls/Containerfile
examples/uki/Containerfile
examples/unified/Containerfile

Fixes conflicts introduced by some `systemd-standalone-sysusers` packages
```
Failed to resolve the transaction:
Problem: installed package systemd-standalone-sysusers-257.3-7.fc43.x86_64 conflicts with systemd-standalone-sysusers provided by systemd-sysusers-257.3-6.fc43.x86_64 from rawhide
- problem with installed package
- package systemd-257.3-6.fc43.x86_64 from rawhide requires systemd-sysusers(x86-64) = 257.3-6.fc43, but none of the providers can be installed
- package systemd-standalone-sysusers-257.3-6.fc43.x86_64 from rawhide conflicts with systemd provided by systemd-257.3-6.fc43.x86_64 from rawhide
- package systemd-udev-257.3-6.fc43.x86_64 from rawhide requires systemd(x86-64) = 257.3-6.fc43, but none of the providers can be installed
- package …
```

Pass `--allowerasing` to dnf for package conflict resolution

---

src/bin/cfsctl.rs
src/erofs/reader.rs
src/repository.rs

Add an internal implementation of `composefs-info objects` and use it from our gc code.  This drops the last runtime dependency on the composefs command-line tools.

gc: use internal objects-for-image code

---

examples/.gitignore
examples/README.md
examples/common/run
examples/unified-secureboot/Containerfile
examples/unified-secureboot/build
examples/unified-secureboot/extra/etc/kernel/uki.conf
examples/unified-secureboot/extra/etc/resolv.conf
examples/unified-secureboot/extra/usr/lib/dracut/dracut.conf.d/37composefs.conf
examples/unified-secureboot/extra/usr/lib/dracut/modules.d/37composefs/composefs-pivot-sysroot.service
examples/unified-secureboot/extra/usr/lib/dracut/modules.d/37composefs/module-setup.sh
examples/unified-secureboot/extra/usr/lib/kernel/install.conf.d/37composefs.conf
examples/unified-secureboot/extra/usr/lib/systemd/network/37-wired.network
examples/unified-secureboot/extra/usr/lib/systemd/system/systemd-growfs-root.service.d/37-composefs.conf
examples/unified-secureboot/run
examples/unified/build

examples/README: Split each sentence on its own line
Signed-off-by: Timothée Ravier <tim@siosm.fr>
---
examples/unified: Bind mount /tmp/sysroot
We need an fs-verity enabled for this operation so mount it from the
host which is more likely to have it (btrfs or ext4).
Signed-off-by: Timothée Ravier <tim@siosm.fr>
---
examples/unified-secureboot: Add Secure Boot signed example
- Based on `unified` example
- Generate keys for Secure Boot signing on demand
- Add mokutil to list Secure Boot related info
- Sign the UKI & systemd-boot
- Generate EUFI VARS including only our own keys and pass it to the EDK2
firwmare with QEMU
Signed-off-by: Timothée Ravier <tim@siosm.fr>

examples/unified-secureboot: Add Secure Boot signed example

---

examples/bls/Containerfile.ubuntu

This is an example of ubuntu image referred to arch example.
[![asciicast](https://asciinema.org/a/RQ32A1rFEVQBVUhnhezOvtKnD.svg)](https://asciinema.org/a/RQ32A1rFEVQBVUhnhezOvtKnD)

Add ubuntu example image

---

src/bin/composefs-pivot-sysroot.rs
src/mount.rs
src/repository.rs

This moves the implementation out of the library and into the command.  That makes sense, since this is not an operation you'd want to do in any other context.
It also adds a commandline option to pivot a different mount point other than `/sysroot`.  GNOME developer Jelle van der Waa is sitting beside me now and he mentions that Arch (mkinitcpio) uses `/new_root`, for example.

composefs-pivot-sysroot improvements

---

Cargo.toml
src/fsverity/ioctl.rs

This commit improves the UX of the error reporting when enabling fs-verity fails because the underlying filesystem does not support this. Here we currently just error with:
```
Inappropriate ioctl for device"
```
with the new code we error with:
```
Filesystem not supported by fs-verity
```
Note that the test relies on the fact that /dev/shm is not supported by fs-verity.
Closes: https://github.com/containers/composefs-rs/issues/59

fsverity: introduce EnableVerifyError::FilesystemNotSupported error

---

.github/workflows/examples.yml
examples/bls/Containerfile.arch
examples/bls/extra/etc/mkinitcpio.conf
examples/bls/extra/usr/lib/initcpio/hooks/composefs
examples/bls/extra/usr/lib/initcpio/install/composefs
examples/uki/Containerfile.arch
examples/uki/extra/etc/mkinitcpio.conf
examples/uki/extra/etc/mkinitcpio.d/linux.preset
examples/uki/extra/usr/lib/initcpio/hooks/composefs
examples/uki/extra/usr/lib/initcpio/install/composefs

Arch Linux uses dracut-ng which by default runs in `hostonly` mode with no easy way to override this behaviour via kernel-install. `hostonly` mode misses virt_blk, ext4 and other kernel modules we would need to pivot to composefs before `switch_root`.
The default initramfs generator for Arch Linux is `mkinitcpio` which by default is without `systemd` and the root filesystem is mounted on `/new_root` instead of `/sysroot`.
Since there is no systemd in the initramfs the root partition has to be hardcoded in the kernel command line and custom composefs hooks to call composefs-pivot-sysroot. The hooks are GPL2 so they can eventually be upstreamed into `mkinitcpio` itself.

examples/bls: use mkinitcpio for initramfs generation

---

.github/workflows/examples.yml
.github/workflows/rust.yml
Cargo.toml
examples/bls/build
examples/uki/build
examples/unified-secureboot/build
examples/unified/build
src/oci/mod.rs

Instead of having podman save our container images to a oci-archive and pulling from that, save ourselves a bunch of work (including a gzip compress/decompress cycle) by pulling directly from `containers-storage:`.
In order to accomplish this, the patch series also adds support for uncompressed and zstd-compressed layers and includes a workaround for https://github.com/containers/skopeo/issues/2563

examples: pull directly from containers storage

---

src/repository.rs

It was not immediately obvious to me where the default repository was
expected to be located.

repository: open_path: include path in error context

---

src/splitstream.rs

This one didn't have a `SAFETY` comment; looking through git log here I do see:
> It no longer does internal buffer allocations when reading tar headers, saving
> another ~10% off the total time to print a merged dumpfile.
However, it looks like that was going from allocation-per-read to "read into a global buffer", which we're still doing here. I didn't measure performance here, but I think
we have other performance worries and it's not worth carrying an `unsafe` for this.
In very hot I/O paths one *can* measure the impact of zero-initializing, but I'm doubtful of that here.
Just looking at the bigger picture here I think
instead of a generic `R: Read` we should take
a `BufReader` and then use `fill_buf` on it,
which is intended for this use case.
Anyways for now just drop the `unsafe`. …

splitstream: Drop an unsafe

---

src/lib.rs
src/uki.rs

This contains a single function to query an appropriate boot label for a UKI image, which might be interesting for supporting bootloaders which don't implement the bootloader specification and is also likely to be used for showing installed bootloader entries in the future.
Nothing in the crate uses this right now, but it's a public API.

uki: new file for querying UKI boot labels

---

Cargo.toml
src/oci/mod.rs
src/util.rs

- remove use of anyhow (everything now uses `std::io::Result`)
- restrict visiblity to `pub(crate)` (except `parse_sha256()`)
- rewrite explicit generics as impl trait arguments
- add tests (100% line coverage)
- add docs

src/util: various cleanups

---

Cargo.toml

In 72d8b71465c6 ("Cargo.toml: update all the things") we randomly raised all of our dependencies to the latest versions, mostly because I don't know what I'm doing when it comes to these things.  That was a mistake: trying to use the latest version of composefs-rs from bootc causes all kinds of dependency conflicts now.
So let's try and do the opposite and try to list the minimum version that:
- is semver compatible with the latest version (so we get updates)
- doesn't break
I tried playing with automated tooling for this but it wasn't easy to get it working without a nightly toolchain (which I don't have setup), and I was also interested in exploring the actual reasons for the requirements, so I went with a simple manual process: I dropped all of the version numbers in [dependencies] …

Cargo.toml: list actual minimum dependencies

---

src/fsverity/mod.rs

This partially fixes #106.
There's a race between the read-write file descriptor being closed,
and the subsequent ioctl to enable fsverify on the read-only copy.
Sometimes the ioctl will return ETXTBSY.  Syncing the data here seems
to be sufficient to resolve this race, but *only* on ext4.  On btrfs,
this is not sufficient.  I *can* fix this on btrfs by doing a
`syncfs()`, but we are trying to avoid doing that here.

fsverity: call sync_data (fdatasync) in test code

---

src/fsverity/mod.rs
src/uki.rs

Otherwise `cargo doc` will complain with `warning: this URL is not a hyperlink`

Use automatic links in docstrings

---

Cargo.toml
src/bin/cfsctl.rs
src/bin/composefs-setup-root.rs
src/dumpfile.rs
src/erofs/composefs.rs
src/erofs/mod.rs
src/erofs/reader.rs
src/erofs/writer.rs
src/fs.rs
src/fsverity/digest.rs
src/fsverity/hashvalue.rs
src/fsverity/mod.rs
src/image.rs
src/oci/image.rs
src/oci/mod.rs
src/oci/tar.rs
src/repository.rs
src/selabel.rs
src/splitstream.rs
src/util.rs
tests/mkfs.rs

This rests upon a massive pile of generics, but it seems to be working.
With these changes the library is now fully agnostic to which hash algorithm we use.  I've tested this and it successfully produces erofs images with the metacopy attributes correctly set for verifying the fs-verity validity of files using sha512.  The examples also correctly boot with a sha512 in the `composefs=` cmdline.
The changes to the bin/ commands to support this will come soon: we need to thoughtfully consider what we want to do here at a higher level....

add complete (library) support for sha-512

---

Cargo.toml
src/bin/cfsctl.rs
src/bin/composefs-setup-root.rs
src/fsverity/hashvalue.rs
src/oci/mod.rs
src/oci/tar.rs
src/repository.rs
src/splitstream.rs

For images with a large number of layers (as is the case for most bootc images) this is a massive win.  I used this as a test:
```sh
skopeo copy docker://quay.io/fedora/fedora-silverblue:42 oci:$HOME/oci/silverblue-42
```
and then
```sh
cfsctl oci pull oci:$HOME/oci/silverblue-42
```
And noticed an improvement from ~90s to ~9s.
Unfortunately the situation isn't much improved for images with a small number of layers (as is the case in our own `examples/` directory).

Add multithread `cfsctl oci pull`

---

crates/cfsctl/src/main.rs
crates/composefs-boot/src/bootloader.rs
crates/composefs-boot/src/write_boot.rs

Grub needs absolute paths to initrd and vmlinuz if we do not have `/boot` in a boot partition, which we do not in bootc.

Allow passing absolute paths to initrd and vmlinuz

---

crates/composefs/src/fsverity/ioctl.rs
crates/composefs/src/fsverity/mod.rs

Reviving the more sane part of #120.
We should provide a clearer error variant here instead of just passing
ETXTBSY through to the caller.

fsverity: Add nicer error variant for ETXTBSY

---

examples/common/install-patched-tools

The fs-verity-enablement patches for mke2fs finally got merged.  Use the upstream branch from install-patched-tools.

examples: install patched mke2fs from upstream

---

crates/composefs/Cargo.toml

We use once_cell because https://github.com/rust-lang/rust/issues/109737
once_cell has a large number of potential locking backends for `no_std` environments.  We were randomly using `critical-section`, which itself requires specifying a backend, which we weren't doing.  So far, we've been protected by this by the fact that we also have once_cell as a transient dependency (via tempfile).
Fix this to just use `std` so that we get locking via the stdlib.

composefs: fix feature flags of once_cell

---

crates/composefs-oci/Cargo.toml

Just keeping up with releases, but this also is prep for us using the `GetRawBlob` API.

Bump containers-image-proxy and oci-spec

---

.github/workflows/examples.yml
crates/cfsctl/src/main.rs
crates/composefs-boot/Cargo.toml
crates/composefs-boot/src/bootloader.rs
crates/composefs-boot/src/cmdline.rs
crates/composefs-boot/src/write_boot.rs
crates/composefs-oci/src/lib.rs
crates/composefs-setup-root/src/main.rs
crates/composefs/src/fsverity/ioctl.rs
crates/composefs/src/fsverity/mod.rs
crates/composefs/src/mount.rs
crates/composefs/src/repository.rs
examples/bls/build
examples/common/check-config
examples/common/repart.d/01-esp.conf
examples/common/repart.d/02-sysroot.conf
examples/common/run-repart
examples/test/run-tests

- adds "insecure" option to repository, allows images which do not have fs-verity enabled
- if `?` is prepended to composefs= cmdline, set repository to insecure
- opportunistically enable fs-verity where appropriate, even if repository is in insecure mode
- add `--insecure` to cfsctl
#87

Make fs-verity optional

---

.github/workflows/rust.yml
crates/composefs/Cargo.toml
crates/composefs/src/fsverity/mod.rs
crates/composefs/src/repository.rs

`enable_verity_raw` is effectively the same as the previous `enable_verity`, it simply calls the underlying ioctl.
`enable_verity_with_retry` will attempt to enable verity an opinionated three times with a 1ms delay between tries when encountering ETXTBSY.  This is generally enough to work around the delay with CLOEXEC in conjunction with fork()->exec().
`enable_verity_maybe_copy` will take ownership of the file descriptor and attempt to enable verity using `enable_verity_with_retry`.  If successful, it returns `VerityFd::Orig(fd)` to designate that the file descriptor is the same one provided by the caller.  If unsuccessful, it will instead copy the data to a new O_TMPFILE and return that via `VerityFd::Copy(fd)`.  It is up to the caller to reconcile how this new file descriptor is to be …

fsverity: split `enable_verity` into multiple related functions

---

crates/composefs-boot/src/bootloader.rs

Since we want to be able to read/write boot entries from bootc

Export function `read_file` as public

---

crates/composefs/src/fsverity/mod.rs

This test was running over 60s on my machine (32 cores); digging in it's because the raw variant was simply not getting anywhere close to hitting 100 successes.
First, rework to use a JoinSet instead of a tokio::join! so we see the completions as they come in instead of waiting for all of them.
Add a hard limit of execution time of 10s.
Add an assertion that the *copy* variant succeeds at least once. For the other two, we can't really make any assertions at all.

tests/verity-forking: Limit execution time to 10s

---

.github/workflows/examples.yml

Not sure why this is failing, but we're not gating on it right now and it's annoying to have to look each time at the red X.

ci: Drop ubuntu/bls

---

crates/composefs-boot/src/lib.rs

This aids our compatibility with existing ostree-containers.
Closes: https://github.com/containers/composefs-rs/issues/164

boot: Empty /sysroot too

---

crates/composefs/src/dumpfile_parse.rs
crates/composefs/src/erofs/reader.rs
crates/composefs/src/mount.rs
crates/composefs/src/mountcompat.rs

Rust 1.89 introduced this new lint[1], fix the handful of places where
it comes up across the repo.
[1] https://blog.rust-lang.org/2025/08/07/Rust-1.89.0/#mismatched-lifetime-syntaxes-lint

Fix warnings for mismatched_lifetime_syntaxes lint

---

crates/composefs-boot/src/os_release.rs

Useful in bootc to get version field for BLS entries

Make `OsReleaseInfo` public

---

crates/composefs-boot/src/uki.rs

Useful in bootc for getting version/version id and maybe more in the future from the UKI

uki: Make function `get_text_section` public
